import { LOCALES } from "../constants";

export default {
  [LOCALES.ENGLISH]: {
    "app.container.homePage.prev": "Prev",
    "app.container.homePage.next": "Next",
    "app.container.homePage.playNow": "Play Now",
    "app.container.homePage.comingSoon": "Coming Soon",
    "app.container.homePage.daoLette": "DAOlette",
    "app.container.homePage.daoDice": "DAOdice",
    "app.container.homePage.daoBlackJack": "DAOblackjack",
    "app.container.homePage.daoLottery": "DAOlottery",
    "app.container.homePage.daoLevels": "DAOlevels",
    "app.container.homePage.daoBaccarat": "DAObaccarat",
    "app.container.homePage.daoWar": "DAOwar",
    "app.container.homePage.daoHoldem": "DAOholdem",
    "app.container.homePage.iconBet": "ICONbet",
    "app.container.footer.copyright": "All rights reserved.",
    "app.container.footer.disclaimer":
      "Disclaimer: If you reside in a location where lottery, gambling, or betting over the internet is illegal, please do not click on anything related to these activities on this site. You must be of legal gambling age, depending on your own jurisdiction, to click on any gambling related items. Recognising that the laws and regulations involving online gaming are different everywhere, players are advised to check with the laws that exist within their own jurisdiction or region to ascertain the legality of the activities which are covered.",
    "app.container.footer.disclaimer2":
      "When you start playing these games, please take note that online gambling and lottery is an entertainment vehicle and that it carries with it a certain degree of financial risk. Players should be aware of these risks and govern themselves accordingly.",
    "app.container.header.games": "Games",
    "app.container.header.daoLette": "ICONbet - DAOlette",
    "app.container.header.daoDice": "ICONbet - DAOdice",
    "app.container.header.daoBlackJack": "ICONbet - DAOblackjack",
    "app.container.header.daoLottery": "ICONbet - DAOlottery",
    "app.container.header.daoLevels": "ICONbet - DAOlevels",
    "app.container.header.about": "About",
    "app.container.header.dividends": "Dividends",
    "app.container.header.tapStaking": "TAP Staking",
    "app.container.header.whitepaper": "Whitepaper",
    "app.container.header.history": "History",
    "app.container.header.help": "Help",
    "app.container.header.faq": "FAQ",
    "app.container.header.gettingStarted": "Getting Started",
    "app.container.header.login": "Login",
    "app.container.header.logout": "Logout",
    "app.container.about.about": "About",
    "app.container.about.aboutContent":
      "ICONbet is a fully decentralized DAO casino, completely owned and operated by members of the ICONbet DAO. \
      Membership of the DAO is represented by TAP token holdings, and TAP tokens can be earned through playing ICONbet\
       or purchasing on third party services.\
      \
      Fairness, transparency, and profit redistribution are essential to ICONbet’s \
      vision, and blockchain enables all these traits that we value. All of the smart\
       contract code that facilitates TAP transactions is viewable in the ICON Tracker,\
        and the founding team is building processes to allow for simple integration of \
        games developed by 3rd parties.",
    "app.container.faq.faq": "FAQ",
    "app.container.gettingStarted.gettingStarted": "GETTING STARTED",
    "app.container.betHistory.betHistory": "BET HISTORY",
    "app.container.betHistory.prev": "Prev",
    "app.container.betHistory.next": "Next",
    "app.container.betHistory.yourHistory": "YOUR HISTORY",
    "app.container.betHistory.gameHistory": "GAME HISTORY",
    "app.container.betHistory.playerAddress": "Player Address",
    "app.container.betHistory.txHash": "TxHash",
    "app.container.betHistory.gameType": "Game Type",
    "app.container.betHistory.betAmount": "Bet Amount",
    "app.container.betHistory.winningNumber": "Winning Number",
    "app.container.betHistory.payout": "Payout",
    "app.container.betHistory.note": "Note",
    "app.container.tapStaking.tapStaking": "TAP STAKING",
    "app.container.tapStaking.selectDesiredWallet": "Select desired wallet",
    "app.container.tapStaking.ledgerNote":
      "Make sure your Ledger device is connected and is unlocked with ICON app running.",
    "app.container.tapStaking.connectToLedger": "Connect To Ledger",
    "app.container.tapStaking.iconNote":
      "Please click on the button below, select your preferred wallet and start staking.",
    "app.container.tapStaking.getICONexWallet": "Get ICONex Wallet",
    "app.container.dividends.dividends": "Dividends",
    "app.container.dividends.myWagers": "My Wagers",
    "app.container.dividends.TodaysTotalTapDistribution":
      "Today's Total TAP Distribution",
    "app.container.dividends.totalWagers": "Total Wagers",
    "app.container.dividends.estimatedShareOfTodaysTap":
      "Estimated share of today's TAP",
    "app.container.dividends.expectedIcxPayout": "Expected ICX Payout",
    "app.container.dividends.totalTapTokensReleased":
      "Total TAP tokens released",
    "app.container.dividends.totalStakedTap": "Total Staked TAP",
    "app.container.dividends.yourTapTokenBalance":
      "Your TAP token balance (Staked/Total)",
    "app.container.dividends.totalIcxDistributedToTapTokenHolders":
      "Total ICX Distributed to TAP token holders",
    "app.container.dividends.excess": "Excess",
    "app.container.dividends.note":
      "Note: Distributions are driven by betting events and will begin at some time after 00: 00 UTC.",
    "app.container.dividends.details": "Details",
    "app.container.dividends.divsDetails": "DIVS DETAILS",
    "app.container.dividends.yesterdaysTotalWagers": "Yesterday’s total Wagers",
    "app.container.dividends.yesterdaysTotalExcess": "Yesterday's total Excess",
    "app.container.dividends.lifetimeTapDividends": "Lifetime TAP Dividends",
    "app.container.dividends.lifetimeWagerWarPrizes":
      "Lifetime Wager War Prizes",
    "app.container.dividends.goBack": "GO BACK",
    "app.container.dividends.gamesVolumeExcess": "Games: Volume | Excess",
    "app.container.dividends.today": "Today",
    "app.container.dividends.yesterday": "Yesterday",
    "app.container.dividends.loading": "loading...",
    "app.container.leaderBoard.player": "Player",
    "app.container.leaderBoard.wagered": "Wagered",
    "app.container.leaderBoard.wagerWar": "Wager War",
    "app.container.roulette.balance": "Balance",
    "app.container.roulette.autoPlay": "Auto Play",
    "app.container.roulette.winChance": "Win Chance",
    "app.container.roulette.spin": "SPIN",
    "app.container.roulette.multiplier": "Multiplier",
    "app.container.roulette.bettingAmount": "Betting Amount",
    "app.container.roulette.maxBet": "Max Bet",
    "app.container.roulette.min": "min",
    "app.container.roulette.max": "max",
    "app.container.roulette.winningAmount": "Winning Amount",
    "app.container.roulette.betOnColor": "Bet on Color",
    "app.container.roulette.betOddorEven": "Bet Odd or Even",
    "app.container.roulette.red": "Red",
    "app.container.roulette.black": "Black",
    "app.container.roulette.odd": "Odd",
    "app.container.roulette.even": "Even",
    "app.container.roulette.betOnNumber": "Bet on Number",
    "app.container.roulette.betLow": "Bet Low",
    "app.container.roulette.betHigh": "Bet High",
    "app.container.roulette.sliderBet": "SLIDER BET",
    "app.container.roulette.muteUnmute": "Mute/Unmute",
    "app.container.roulette.winningNumber": "Winning Number",
    "app.container.roulette.you": "You",
    "app.container.roulette.won": "Won!",
    "app.container.roulette.lost": "Lost.",
    "app.container.roulette.resubmittingBet": "Resubmitting your bet in",
    "app.container.roulette.seconds": "seconds",
    "app.container.roulette.txnFail": "Transaction Failed",
    "app.container.roulette.txnDetail": "Transaction Detail",
    "app.container.roulette.placingBet": "Placing bet. Please wait...",
    "app.container.roulette.noTrackerResponse":
      "No response from tracker. You may check the transaction status",
    "app.container.roulette.here": "here",
    "app.container.daodice.balance": "Balance",
    "app.container.daodice.autoPlay": "Auto Play",
    "app.container.daodice.winChance": "Win Chance",
    "app.container.daodice.placeBet": "PLACE BET",
    "app.container.daodice.placingBet": "PLACING BET",
    "app.container.daodice.multiplier": "Multiplier",
    "app.container.daodice.bettingAmount": "Bet Amount",
    "app.container.daodice.min": "min",
    "app.container.daodice.max": "max",
    "app.container.daodice.winningAmount": "Winning Amount",
    "app.container.daodice.sideBet": "Sidebet",
    "app.container.daodice.oneIcon": "One Icon",
    "app.container.daodice.twoIcon": "Two Icon",
    "app.container.daodice.matchingDigit": "Matching Digit",
    "app.container.daodice.result": "Result",
    "app.container.daodice.won": "Won!",
    "app.container.daodice.lost": "Lost.",
    "app.container.gettingStarted.header": "Getting Started",
    "app.container.gettingStarted.dontShow": "Don't show this to me again",
    "app.container.gettingStarted.note":"Note: You can find this under the help menu for future reference." 
  }
};
